version: '3'
services:
  app:
    build:
      context: '.'
      args:
        - MYSQL_USERNAME=$MYSQL_USERNAME
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_HOSTNAME=$MYSQL_HOSTNAME
        - MYSQL_PORT=$MYSQL_PORT
        - SSL_ENABLED=$SSL_ENABLED
        - SSL_KEY=$SSL_KEY
        - SSL_CERTIFICATE=$SSL_CERTIFICATE
        - SERVER_PORT=$SERVER_PORT
        - SERVER_ADDRESS=$SERVER_ADDRESS
        - WEBSOCKET_PORT=$WEBSOCKET_PORT
        - AUTO_ACCEPT_CONNECTION=$AUTO_ACCEPT_CONNECTION
        - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
    restart: always
    ports:
      - "$WEBSOCKET_PORT:$WEBSOCKET_PORT"
    environment:
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_HOSTNAME=$MYSQL_HOSTNAME
      - MYSQL_PORT=$MYSQL_PORT
      - SSL_ENABLED=$SSL_ENABLED
      - SSL_KEY=$SSL_KEY
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SERVER_PORT=$SERVER_PORT
      - SERVER_ADDRESS=$SERVER_ADDRESS
      - WEBSOCKET_PORT=$WEBSOCKET_PORT
      - AUTO_ACCEPT_CONNECTION=$AUTO_ACCEPT_CONNECTION
      - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
