version: '3'
services:
  app:
    build:
      context: '.'
      dockerfile: 'docker/node'
      args:
        - MYSQL_DATABASE=$MYSQL_DATABASE
        - MYSQL_PORT=$MYSQL_PORT
        - SSL_ENABLED=$SSL_ENABLED
        - SSL_KEY=$SSL_KEY
        - SSL_CERTIFICATE=$SSL_CERTIFICATE
        - SERVER_PORT=$SERVER_PORT
        - SERVER_ADDRESS=0.0.0.0
        - WEBSOCKET_PORT=$WEBSOCKET_PORT
        - AUTO_ACCEPT_CONNECTION=$AUTO_ACCEPT_CONNECTION
        - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
    restart: always
    ports:
      - "$WEBSOCKET_PORT:$WEBSOCKET_PORT"
    environment:
      - MYSQL_USERNAME=dev
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=$MYSQL_PORT
      - SSL_ENABLED=$SSL_ENABLED
      - SSL_KEY=$SSL_KEY
      - SSL_CERTIFICATE=$SSL_CERTIFICATE
      - SERVER_PORT=$SERVER_PORT
      - SERVER_ADDRESS=$SERVER_ADDRESS
      - WEBSOCKET_PORT=$WEBSOCKET_PORT
      - AUTO_ACCEPT_CONNECTION=$AUTO_ACCEPT_CONNECTION
      - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
    networks:
      main:
        ipv4_address: 172.25.0.2
        aliases:
          - node
  mysql:
    build:
      context: .
      dockerfile: 'docker/mysql'
      args:
        - SERVER_ADDRESS=172.25.0.2
        - SERVER_PORT=$SERVER_PORT
    platform: linux/amd64
    ports:
      - "$MYSQL_PORT:$MYSQL_PORT"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PORT=$MYSQL_PORT
      - SERVER_PORT=$SERVER_PORT
      - SERVER_ADDRESS=$SERVER_ADDRESS
    networks:
      main:
        ipv4_address: 172.25.0.3
        aliases:
          - mysql
    volumes:
      - ./bin:/docker-entrypoint-initdb.d
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1